# Generated by Django 6.0.2 on 2026-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterModelOptions(
            name='customusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customusers',
            name='user_type',
            field=models.CharField(choices=[('employer', '👔 Работодатель'), ('seeker', '🔍 Соискатель')], default='seeker', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
