# Generated by Django 6.0.2 on 2026-02-19 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('work_type', models.CharField(choices=[('remote', '🌍 Удаленная работа'), ('office', '🏢 В офисе работодателя'), ('hybrid', '🔄 Гибридный формат')], default='remote', max_length=10, verbose_name='Тип занятости')),
                ('experience', models.CharField(choices=[('no', '🙅 Без опыта'), ('junior', '🌱 Junior'), ('middle', '🌳 Middle'), ('senior', '🌲 Senior')], default='junior', max_length=10, verbose_name='Опыт работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.category', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at', '-is_featured'],
                'indexes': [models.Index(fields=['-created_at'], name='main_vacanc_created_bbf814_idx'), models.Index(fields=['is_active', 'work_type'], name='main_vacanc_is_acti_43fb9d_idx')],
            },
        ),
    ]
